rough api added to Test.c
Phabbits/CNIT315 pull request #21
Opened 2021-04-28 23:17 UTC by ndoubleg

2021-04-28 23:37 UTC, Phabbits requested changes
Look over this.

2021-04-28 23:37 UTC, Phabbits commented on Test.C
> +  sprintf(char *fields, "player_name=%s&score=%d&seed=%d&version=%d", &playerName, &score, &seed, &version);
fields is a string or character array in C. `char *fields` is not how you initiate an array. Please initiate the array outside of the `sprintf` function. This is why you are getting `fields` was not declared in this scope on line 674

2021-04-29 18:42 UTC, ndoubleg commented on Test.C
> +  sprintf(char *fields, "player_name=%s&score=%d&seed=%d&version=%d", &playerName, &score, &seed, &version);
```suggestion
void addScore(char playerName[NAME_LENGTH], int score, int seed, int version){
  CURL *curl;
  CURLcode res;
  
  char fields[50];
  
  /* Creates the fields in which the scores are saved to the website */
  sprintf(fields, "player_name=%s&score=%d&seed=%d&version=%d", playerName, score, seed, version);
```

2021-04-29 18:42 UTC, ndoubleg commented on Test.C
> +  sprintf(char *fields, "player_name=%s&score=%d&seed=%d&version=%d", &playerName, &score, &seed, &version);
to print the fields, where exactly would the `printf("%s", fields);` go in this?
edit: was able to figure out.

2021-04-29 18:42 UTC, ndoubleg commented on Test.C
> +  sprintf(char *fields, "seed=%d&version=%d", &seed, &version);
```suggestion
  char fields[50];
  
  /* Creates the fields in which the scores saved on the website are called upon */
  sprintf(fields, "seed=%d&version=%d", seed, version);
```

2021-04-29 18:48 UTC, ndoubleg commented on Test.C
> +  printf("player_name=%s&score=%d&seed=%d&version=%d", &playerName, &score, &seed, &version)
```suggestion
```

2021-04-29 18:48 UTC, Phabbits requested changes

2021-04-29 18:48 UTC, Phabbits commented on Test.C
> +	void getScores(int seed, int version);
We can just hardcode defaults right now.
```suggestion
	void getScores(1, 0.01);
```

2021-04-29 18:48 UTC, Phabbits commented on Test.C
> +	void addScore(char playerName, int score, int seed, int version);
Lets just hardcode defaults for now.
```suggestion
	void addScore(player.name, player.currentCredits, 1, 0.01);
```

2021-04-29 20:00 UTC, Phabbits approved these changes

2021-04-29 20:00 UTC, merged